title: The 100 Club Documentation
remote_theme: just-the-docs/just-the-docs
logo: ".assets/NavLogo.png"
# url: "https://sosimplysean.github.io/professional-orbital-the100club/"

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Check out the live platform":
    - "https://the100club.netlify.app/"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true